- name: Run todo app
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: latest
    become: yes

  - name: Install python3
    ansible.builtin.yum:
      name: python3
    become: yes

  - name: Install poetry
    ansible.builtin.shell:
      cmd: 'curl -sSL https://install.python-poetry.org | python3 -'
    become: yes

  - name: Create directory for app
    ansible.builtin.file:
      path: /opt/todoapp
      state: directory
      owner: ec2-user
    become: yes

  - name: Checkout the code with git
    ansible.builtin.git:
      dest: /opt/todoapp
      version: 'module-4'
      repo: 'https://github.com/rhimcg/DevOps-Course-Starter.git'

  - name: install dependencies
    ansible.builtin.shell: poetry_install.sh


